baseURL: "https://www.dbraccia.com/"
publishDir: "dombraccia.github.io"
languageCode: "en-us"
title: "Personal site for Domenick J. Braccia"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxx-x
disqusShortname:
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  favicon: "/images/me.jpg"
  #description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2021"

  # Navbar Menus
  customMenus:
    - name: "CV"
      Url: "/CV"
    - name: "Blog"
      Url: "/blog"

  # social
  name: "Domenick"
  github: "https://github.com/dombraccia"
  linkedin: "https://linkedin.com/in/dombraccia"
  twitter: "https://twitter.com/dombraccia"

  # About
  profile_image: "/images/me.jpg"
  descripe_l1_person: "I am a PhD candidate at the University of Maryland, studying bioinformatics and computational biology. My current research focus is on characterizing health relevant functions of the gut microbiome." 
  descripe_l2_person: "Generally, I am interested in using computational tools to answer biological questions. I also enjoy creating algorithms to solve a particular problems in biological sequence analysis."
  useresume: false 
  resume: ""

  # Things I do
  usedothings: false
  Things:
    - logo: fab fa-python
      title: Python
      description: I write programs using R

    - logo: fas fa-robot
      title: Machine learning
      description: I train robust models for various tasks.

    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web

  #Description for seo. If you want to show description in your listing or single page, let's make it true
  showdescription: false
