baseURL: "https://example.com"
languageCode: "en-us"
title: "Personal site for Domenick J. Braccia"
theme: "hugo-profile"

#googleanalytics: UA-xxxxxxxx-x
disqusShortname: Domenick
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: ""
  description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2020"

  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "/blog"
    
  # social
  name: "Hugo-profile"
  github: "https://github.com/dombraccia"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/dombraccia"
  instagram: "https://instagram.com"
  facebook: "https://facebook.com"

  # About
  profile_image: ""
  descripe_l1_person: "A high performance hugo theme for personal website and blog. It is a single page portfolio."
  descripe_l2_person: "This is just a example for about section. You can easily change with the help of cofig file."
  job: "PhD candidate"
  useresume: true
  resume: ""

  # Things I do
  usedothings: true
  Things:
    - logo: fab fa-python
      title: Python
      description: I build something beautiful using Python.

    - logo: fas fa-robot
      title:  Machine learning 
      description: I train robust models for various tasks. 

    - logo: fab fa-html5
      title: Things for web 
      description: I love to build things for web

  #blog ( Description for seo. If you want to show description in your blog post, let's make it true)
  showdescription: true

Author:
  name: "Domenick"
  website: "https://github.com/dombraccia"
